name: "Nix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    - uses: cachix/cachix-action@v12
      with:
        name: hannes-hochreiner
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --extra-experimental-features nix-command --extra-experimental-features flakes --accept-flake-config